from . import commands
from . import registration
from . import menu
from . import task1
from . import task2
from . import task3
from . import task4
from . import task5
from . import task6
from . import task7